// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use diesel::prelude::*;

#[derive(Queryable, Debug, Selectable)]
#[diesel(table_name = organisations)]
pub struct Organisation {
    pub id: i32,
    pub name: String,
    pub owner: i32,
}

#[derive(Queryable, Debug, Selectable)]
#[diesel(table_name = tokens)]
pub struct Token {
    pub id: i32,
    pub hash: String,
    pub ttype: i32,
    pub owner: i32,
    pub sub: String,
}

#[derive(Queryable, Debug, Selectable)]
#[diesel(table_name = user_orgs)]
pub struct UserOrg {
    pub id: i32,
    pub uid: i32,
    pub oid: i32,
}

#[derive(Queryable, Debug, Selectable)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i32,
    pub login: String,
    pub hash: String,
}

