// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `comp_data` table.
    ///
    /// (Automatically generated by Diesel.)
    comp_data (id) {
        /// The `id` column of the `comp_data` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `queues` column of the `comp_data` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        queues -> Bytea,
    }
}

diesel::table! {
    /// Representation of the `comp_staff_links` table.
    ///
    /// (Automatically generated by Diesel.)
    comp_staff_links (uid, cid) {
        /// The `uid` column of the `comp_staff_links` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int4,
        /// The `cid` column of the `comp_staff_links` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        cid -> Int4,
    }
}

diesel::table! {
    /// Representation of the `competitions` table.
    ///
    /// (Automatically generated by Diesel.)
    competitions (id) {
        /// The `id` column of the `competitions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `title` column of the `competitions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `public` column of the `competitions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        public -> Bool,
        /// The `organisation` column of the `competitions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        organisation -> Int4,
        /// The `start_date` column of the `competitions` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        start_date -> Nullable<Timestamp>,
        /// The `ends_date` column of the `competitions` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        ends_date -> Nullable<Timestamp>,
        /// The `place` column of the `competitions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        place -> Nullable<Text>,
        /// The `descr` column of the `competitions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        descr -> Nullable<Text>,
        /// The `scheme` column of the `competitions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        scheme -> Int4,
        /// The `queues` column of the `competitions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        queues -> Int4,
        /// The `status` column of the `competitions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Int4,
    }
}

diesel::table! {
    /// Representation of the `organisations` table.
    ///
    /// (Automatically generated by Diesel.)
    organisations (id) {
        /// The `id` column of the `organisations` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `organisations` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `owner` column of the `organisations` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        owner -> Int4,
    }
}

diesel::table! {
    /// Representation of the `tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    tokens (id) {
        /// The `id` column of the `tokens` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `hash` column of the `tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hash -> Text,
        /// The `ttype` column of the `tokens` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        ttype -> Int4,
        /// The `owner` column of the `tokens` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        owner -> Int4,
        /// The `sub` column of the `tokens` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        sub -> Text,
        /// The `created_at` column of the `tokens` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `expire_at` column of the `tokens` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        expire_at -> Timestamp,
    }
}

diesel::table! {
    /// Representation of the `user_orgs` table.
    ///
    /// (Automatically generated by Diesel.)
    user_orgs (uid, oid, perm) {
        /// The `uid` column of the `user_orgs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Int4,
        /// The `oid` column of the `user_orgs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        oid -> Int4,
        /// The `perm` column of the `user_orgs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        perm -> Text,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `login` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        login -> Text,
        /// The `selfname` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        selfname -> Text,
        /// The `hash` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hash -> Text,
    }
}

diesel::joinable!(comp_data -> competitions (id));
diesel::joinable!(comp_staff_links -> competitions (cid));
diesel::joinable!(comp_staff_links -> users (uid));
diesel::joinable!(competitions -> organisations (organisation));
diesel::joinable!(organisations -> users (owner));
diesel::joinable!(tokens -> users (owner));
diesel::joinable!(user_orgs -> organisations (oid));
diesel::joinable!(user_orgs -> users (uid));

diesel::allow_tables_to_appear_in_same_query!(
    comp_data,
    comp_staff_links,
    competitions,
    organisations,
    tokens,
    user_orgs,
    users,
);
